In [92]:
# NumPy allows fast numerical computation using vectorized operations
# It is the foundation of Pandas, Scikit-Learn, TensorFlow.
import numpy as np

In [65]:
# why numpy
lis1 = [1,2,3,4,5]
arr1 = np.array([1,2,3,4,5])

In [66]:
print(type(lis1))
print(type(arr1))
lis1

<class 'list'>
<class 'numpy.ndarray'>


[1, 2, 3, 4, 5]

In [67]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10]


In [68]:
arr3 = np.array([[1,2,3],
                [4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [69]:
# other ways to create array
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
# properties of array
print("Shape:", arr3.shape)
print("Size:", arr3.size)
print("Dimensions:", arr3.ndim)
print("Data type:", arr3.dtype)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [73]:
print(arr2[0])        # First element
print(arr2[-1])       # Last element
print(arr2[1:4])      # Slicing

1
10
[2 3 4]


In [74]:
print(arr3[0])        # First row
print(arr3[:, 1])     # Second column

[1 2 3]
[2 5]


In [75]:
print(arr1 + 10)
print(arr1 * 2)
print(arr1 / 2)

[11 12 13 14 15]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [76]:
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Max:", arr1.max())
print("Min:", arr1.min())

Sum: 15
Mean: 3.0
Max: 5
Min: 1


In [85]:
arr3 = np.arange(1, 7)
print(arr3)

reshaped = arr3.reshape(2, 3)  # change shape
print(reshaped)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [86]:
flat = reshaped.flatten()   # convert to 1d
print(flat)

[1 2 3 4 5 6]


In [87]:
arr4 = np.arange(1,21)
print(arr4)
reshaped4 = arr4.reshape(4,5)
print(reshaped4)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [88]:
print(reshaped4.shape)

(4, 5)


In [89]:
print(reshaped4.mean())

10.5


In [90]:
print(reshaped4.max())

20


In [91]:
print(reshaped4[:,1])  # for access second column 

[ 2  7 12 17]


In [93]:
print(reshaped4 + 10)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [94]:
arr5 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])


In [98]:
print(arr5[1])   # 2nd row

[40 50 60]


In [100]:
print(arr5[:,2])    # 3rd column

[30 60 90]


In [101]:
arr6 = np.array([1, 2, 3, 4, 5])
print(arr6 + 5)  # add 5 to each elements
print(arr6 * 3) # multiply by 3 each elements

[ 6  7  8  9 10]
[ 3  6  9 12 15]


In [106]:
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())

15
3.0
5
1


In [117]:
arr7 = np.arange(1,13)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
print(arr7.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [120]:
print(arr7.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
